
/* 
========================================================
DDL SCRIPT: Create bronze tables
========================================================
Script Purpose:
   This script creates a table in the bronze schema, dropping
   existing tables if they already exist.
   Run the script to redefine the DDL structure of bronze Tables.
========================================================
*/

 IF OBJECT_ID('bronze.crm_cust_info', 'U') IS NOT NULL
 drop table bronze.crm_cust_info;

 GO
CREATE TABLE bronze.crm_cust_info(
cst_id INT,
cst_key NVARCHAR(50),
cst_firstname NVARCHAR(50),
cst_lastname NVARCHAR(50),
cst_marital_status NVARCHAR(50),
cst_gndr NVARCHAR(10),
cst_create_date DATE,
);


 IF OBJECT_ID('bronze.crm_prd_info' , 'U') IS NOT NULL
 drop table bronze.crm_prd_info;

 GO
CREATE TABLE bronze.crm_prd_info(
prd_id INT,
prd_key NVARCHAR(50),
prd_nm NVARCHAR(50),
prd_cost INT,
pd_line NVARCHAR(10),
prd_start_date DATE,
prd_end_date DATE
);

GO

 IF OBJECT_ID('bronze.crm_sales_details' , 'U') IS NOT NULL
 drop table bronze.crm_sales_details;

 GO

CREATE TABLE bronze.crm_sales_details(
sls_ord_num NVARCHAR(50),
sls_prd_key NVARCHAR(50),
sls_cust_id INT,
sls_orders_dt INT,
sls_ship_dt DATE,
sls_due_dt DATE,
sls_sales INT,
sls_quantity INT,
sls_price INT 
);
GO

 IF OBJECT_ID('bronze.erp_cust_az12', 'U') IS NOT NULL
 drop table bronze.erp_cust_az12;

 GO 

CREATE TABLE  bronze.erp_cust_az12
(
CID NVARCHAR(50),
BDATE DATE,
GEN NVARCHAR(10)
);
GO

 IF OBJECT_ID('bronze.erp_loc_a101', 'U') IS NOT NULL
 drop table bronze.erp_loc_a101;

GO

CREATE TABLE bronze.erp_loc_a101
(
CID NVARCHAR(50),
CNTRY NVARCHAR(50)
);

GO

 IF OBJECT_ID('bronze.erp_px_cat_g1v2', 'U') IS NOT NULL
 drop table bronze.erp_px_cat_g1v2;
GO

CREATE TABLE bronze.erp_px_cat_g1v2
(
ID NVARCHAR(50),
CAT NVARCHAR(50),
SUBCAT NVARCHAR(50),
MAINTENANCE NVARCHAR(10)
);


